-- Database export: db_build_safe
-- Date: 2026-09-03 16:13:08
-- Generated by DBX

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `admin_user` (
  `user_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '用户名',
  `password` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '密码',
  `salt` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '安全符',
  `img` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '头像',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `realname` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '真实姓名',
  `num` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '员工编号',
  `mobile` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '手机号',
  `email` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '邮箱',
  `sex` int DEFAULT NULL COMMENT '0 未选择 1 男 2 女 ',
  `dept_id` int DEFAULT NULL COMMENT '部门',
  `post` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '岗位',
  `status` int DEFAULT '2' COMMENT '状态,0禁用,1正常,2未激活',
  `parent_id` bigint DEFAULT '0' COMMENT '直属上级ID',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `last_login_ip` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '最后登录IP 注意兼容IPV6',
  `old_user_id` bigint DEFAULT NULL,
  `tenant_id` int NOT NULL,
  `project_id` int DEFAULT NULL,
  PRIMARY KEY (`user_id`) USING BTREE,
  KEY `parent_id` (`parent_id`) USING BTREE,
  KEY `dept_id` (`dept_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=15104 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='用户表';

CREATE TABLE `ai_alert` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `alert_time` datetime DEFAULT NULL COMMENT '警报时间',
  `alert_type` varchar(50) DEFAULT NULL COMMENT '警报类型',
  `alert_content` varchar(500) DEFAULT NULL COMMENT '警报内容',
  `alert_img` varchar(255) DEFAULT NULL COMMENT '警报图片路径',
  `handle_by` varchar(100) DEFAULT NULL COMMENT '处置人',
  `handle_content` varchar(500) DEFAULT NULL COMMENT '处置内容',
  `handle_time` datetime DEFAULT NULL COMMENT '处置时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新人ID',
  `alert_status` varchar(50) DEFAULT NULL COMMENT '警报状态 1.未处置 2.处置中 3.已处置',
  `equipment_id` int DEFAULT NULL COMMENT '设备ID',
  PRIMARY KEY (`id`),
  KEY `idx_equipment_id` (`equipment_id`) COMMENT '设备ID索引',
  KEY `idx_alert_time` (`alert_time`) COMMENT '警报时间索引',
  KEY `idx_create_time` (`create_time`) COMMENT '创建时间索引'
) ENGINE=InnoDB AUTO_INCREMENT=89 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI图片识别报警表';

CREATE TABLE `coze_chat_conversation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `conversation_id` varchar(64) NOT NULL COMMENT 'Coze 会话 ID',
  `title` varchar(256) DEFAULT '新对话' COMMENT '会话标题',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_conversation_id` (`conversation_id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Coze 会话记录表';

CREATE TABLE `coze_document` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `doc_id` varchar(128) DEFAULT NULL,
  `doc_name` varchar(256) DEFAULT NULL,
  `doc_url` varchar(512) DEFAULT NULL,
  `bstudio_create_time` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_doc_id` (`doc_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `device_camera` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '摄像头设备ID',
  `asset_id` int DEFAULT NULL COMMENT '设备ID',
  `status` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '0' COMMENT '状态（1：在线，0：离线）',
  `is_enable` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '1' COMMENT '当前设备是否启用（1：启用，0：禁用）',
  `wvp_open_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'wvp视频播放地址',
  `ai_monitor_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'AI监测类型（字典项）',
  `sort` int DEFAULT '0' COMMENT '排序序号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='摄像头设备信息表';

CREATE TABLE `device_data` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID（自增）',
  `device_id` varchar(64) NOT NULL COMMENT '设备ID（与JSON中的id对应）',
  `device_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '数据类型（与JSON中的type对应，可选）',
  `properties` json NOT NULL COMMENT '动态属性（JSON格式存储）',
  `report_time` datetime NOT NULL COMMENT '数据上报时间',
  PRIMARY KEY (`id`),
  KEY `idx_device_time` (`device_id`,`report_time`),
  KEY `idx_data_type` (`device_code`)
) ENGINE=InnoDB AUTO_INCREMENT=3521 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备数据存储表（支持动态属性）';

CREATE TABLE `elevator_data` (
  `asset_id` int DEFAULT NULL COMMENT '设备ID',
  `monitor_time` datetime DEFAULT NULL COMMENT '监测时间',
  `before_lock` varchar(10) DEFAULT NULL COMMENT '前门锁状态 0 关闭  1 开启',
  `after_lock` varchar(10) DEFAULT NULL COMMENT '后门锁状态0 关闭  1 开启',
  `x_angle` double DEFAULT NULL COMMENT 'X倾角（单位是度）',
  `y_angle` double DEFAULT NULL COMMENT 'Y倾角（单位是度）',
  `height` int DEFAULT NULL COMMENT '行程高度（单位是M）',
  `speed` double DEFAULT NULL COMMENT '速度（单位是m/s）',
  `weight` double DEFAULT NULL COMMENT '吊重（单位是t）',
  `weight_percent` double DEFAULT NULL COMMENT '本次载重百分比',
  `start_height` double DEFAULT NULL COMMENT '起点高度',
  `end_height` double DEFAULT NULL COMMENT '终点高度',
  `avg_speed` double DEFAULT NULL COMMENT '平均速度',
  `lifting_direction` varchar(10) DEFAULT NULL COMMENT '起升方向(1-静止，3-下 2-上) ',
  `warning_state` varchar(10) DEFAULT NULL COMMENT '是否违章（0-正常 1-身份未认证 2-重量违章）',
  `number_of_people` int DEFAULT NULL COMMENT '人数',
  `wind` double DEFAULT NULL COMMENT '风速',
  KEY `idx_monitor_time` (`monitor_time`),
  KEY `idx_equipment_id` (`asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='升降电梯设备实时数据表';

CREATE TABLE `elevator_info` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `asset_id` int DEFAULT NULL COMMENT '设备id',
  `rated_weight` double DEFAULT NULL COMMENT '额定重量',
  `basic_height` double DEFAULT NULL COMMENT '基本高度',
  `ascending_speed` double DEFAULT NULL COMMENT '起升速度',
  `rated_load` int DEFAULT NULL COMMENT '额定载重人数',
  `cabin_size` double DEFAULT NULL COMMENT '吊笼尺寸',
  `max_ascending_height` double DEFAULT NULL COMMENT '最大起升高度',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='电梯信息表';

CREATE TABLE `elevator_work` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `asset_id` int DEFAULT NULL COMMENT '设备id',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `weight` double DEFAULT NULL COMMENT '载重',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `number_of_people` int DEFAULT NULL COMMENT '人数',
  `start_floor` int DEFAULT NULL COMMENT '开始楼层',
  `end_floor` int DEFAULT NULL COMMENT '呼叫楼层',
  `wind` double DEFAULT NULL COMMENT '风速',
  `speed` double DEFAULT NULL COMMENT '升降机运行速度',
  `angle` double DEFAULT NULL COMMENT '倾斜角度',
  `angle_y` double DEFAULT NULL COMMENT 'y倾斜角度',
  `start_height` double DEFAULT NULL COMMENT '本次起升起点高度',
  `end_height` double DEFAULT NULL COMMENT '本次起升终点高度',
  `height` double DEFAULT NULL COMMENT '本次起升的行程高度',
  `direction` varchar(50) DEFAULT NULL COMMENT '本次起升方向',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9310 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='升降机工作记录';

CREATE TABLE `environment_monitor_point` (
  `id` int NOT NULL AUTO_INCREMENT,
  `point_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '监测点编号',
  `point_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '监测点名称',
  `device_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `unit` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '单位',
  `alarm_upper` decimal(10,0) DEFAULT NULL COMMENT '报警上限阀值',
  `alarm_lower` decimal(10,0) DEFAULT NULL COMMENT '报警下限阀值',
  `warn_upper` decimal(10,0) DEFAULT NULL COMMENT '预警上限',
  `warn_lower` decimal(10,0) DEFAULT NULL COMMENT '预警下限',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2851 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='环境监测-监测点设置';

CREATE TABLE `environment_value` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `monitor_point_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '监测点类型',
  `asset_id` bigint DEFAULT NULL,
  `value` double DEFAULT NULL COMMENT '监测值',
  `monitor_time` datetime DEFAULT NULL COMMENT '监测时间',
  `date_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'realTime' COMMENT '日期类型',
  `max_value` double DEFAULT NULL,
  `min_value` double DEFAULT NULL,
  `avg_value` double DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_monitor_time` (`monitor_time`) USING BTREE COMMENT '监测时间索引',
  KEY `idx_monitor_point_id` (`monitor_point_code`) COMMENT '监测点ID索引',
  KEY `date_type` (`date_type`)
) ENGINE=InnoDB AUTO_INCREMENT=2912 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='环境监测数据';

CREATE TABLE `equipment_assets` (
  `asset_id` int NOT NULL AUTO_INCREMENT COMMENT '资产ID',
  `asset_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资产编号',
  `asset_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资产名称',
  `location_id` int DEFAULT NULL COMMENT '资产位置',
  `type_id` int NOT NULL COMMENT '设备类型',
  `brand` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '品牌',
  `specification` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '规格',
  `model` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '型号',
  `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '状态 字典项1：正常 0：报废',
  `sort` int DEFAULT NULL COMMENT '排序',
  `level` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '重要程度 字典项',
  `factory` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '生产厂家',
  `production_date` date DEFAULT NULL COMMENT '出厂日期',
  `supplier` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '供货商',
  `supply_date` date DEFAULT NULL COMMENT '供货日期',
  `acceptance_date` date DEFAULT NULL COMMENT '验收日期',
  `install_date` date DEFAULT NULL COMMENT '安装日期',
  `start_date` date DEFAULT NULL COMMENT '启动日期',
  `scrap_pre` date DEFAULT NULL COMMENT '报废预期',
  `service_term` int DEFAULT NULL COMMENT '保修期限',
  `scrap_date` date DEFAULT NULL COMMENT '报废日期',
  `service_date` date DEFAULT NULL COMMENT '保修截止日期',
  `original` int DEFAULT NULL COMMENT '设备原值',
  `original_pre` int DEFAULT NULL COMMENT '评估价值',
  `asset_pic` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '资产照片',
  `remarks` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注说明',
  `create_time` datetime NOT NULL,
  `create_user_id` bigint NOT NULL,
  `update_time` datetime DEFAULT NULL,
  `update_user_id` bigint DEFAULT NULL,
  `platform` int DEFAULT NULL COMMENT '对接平台',
  `plane_coordinate` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '相对位置大屏',
  `plane_coordinate_pc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '相对位置pc',
  `platform_eq_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '平台设备标识',
  `offline_date` datetime DEFAULT NULL COMMENT '上下线时间',
  `offline_status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '状态:1在线，0离线',
  `open_status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '开启状态',
  PRIMARY KEY (`asset_id`) USING BTREE,
  KEY `sort` (`sort`),
  KEY `asset_code` (`asset_code`),
  KEY `platform_eq_code` (`platform_eq_code`),
  KEY `idx_type_offline` (`type_id`,`offline_status`)
) ENGINE=InnoDB AUTO_INCREMENT=380 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='设备资产';

CREATE TABLE `equipment_location` (
  `location_id` int NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `location_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '编码',
  `location_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '位置名称',
  `location_pid` int NOT NULL DEFAULT '0' COMMENT '父级ID',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `create_time` datetime NOT NULL,
  `create_user_id` bigint NOT NULL,
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `update_user_id` bigint DEFAULT NULL,
  PRIMARY KEY (`location_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='设备位置信息';

CREATE TABLE `equipment_monitor_point` (
  `id` int NOT NULL AUTO_INCREMENT,
  `point_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '监测点编号',
  `point_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '监测点名称',
  `device_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `monitor_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '监测项类型 字典项 1：基坑监测、2：塔机监测、3；升降机监测、9：环境监测',
  `monitor_son_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '检测项子类型 字典项：1：PM2.5、2：PM10、3：噪音、',
  `equipment_id` int DEFAULT NULL COMMENT '设备名称',
  `statistical_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '2' COMMENT '统计类型',
  `unit` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '单位',
  `sort` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '99' COMMENT '排序',
  `alarm_upper` decimal(10,0) DEFAULT NULL COMMENT '报警上限阀值',
  `alarm_lower` decimal(10,0) DEFAULT NULL COMMENT '报警下限阀值',
  `warn_upper` decimal(10,0) DEFAULT NULL COMMENT '预警上限',
  `warn_lower` decimal(10,0) DEFAULT NULL COMMENT '预警下限',
  `is_spray_system` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '是否关联喷洒系统 1：是 0：否  非字典项',
  `start_spray_value` decimal(10,0) DEFAULT NULL COMMENT '启动喷淋值',
  `close_spray_value` decimal(10,0) DEFAULT NULL COMMENT '关闭喷淋值',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_user_id` bigint DEFAULT NULL COMMENT '创建人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新人',
  `range_time` int DEFAULT NULL COMMENT '警报范围时间 单位秒',
  `status` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '状态（0：无效 1：启用 ）',
  `point_location` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2867 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='设备监测-监测点设置';

CREATE TABLE `equipment_offline` (
  `id` int NOT NULL AUTO_INCREMENT,
  `equipment_id` int DEFAULT NULL COMMENT '设备id',
  `status` int DEFAULT NULL COMMENT '状态1上线，2离线',
  `monitor_time` datetime DEFAULT NULL COMMENT '检测时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2978 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='设备上下线记录表';

CREATE TABLE `equipment_type` (
  `type_id` int NOT NULL AUTO_INCREMENT,
  `type_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '类型编号',
  `type_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '类型名称',
  `type_pid` int NOT NULL DEFAULT '0' COMMENT '父id',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `create_time` datetime NOT NULL,
  `create_user_id` bigint NOT NULL,
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `update_user_id` bigint DEFAULT NULL,
  PRIMARY KEY (`type_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=520 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='设备类型信息';

CREATE TABLE `monitor_point_alert` (
  `id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `monitor_point_id` int DEFAULT NULL COMMENT '监测点id',
  `equipment_id` int DEFAULT NULL COMMENT '设备id',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间，即监测时间',
  `monitor_data` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '监测数据(报警值)',
  `recovery_data` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '监测数据(恢复值)',
  `recovery_time` datetime DEFAULT NULL COMMENT '监测数据(恢复时间)',
  `content` varchar(2555) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '内容',
  `monitor_log` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '日志信息',
  `handle_time` datetime DEFAULT NULL COMMENT '处理时间',
  `handle_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '处理人',
  `handle_measures` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '处理措施',
  `handle_conclu` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '处理后结论',
  `handle_state` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '处理状态（0：未处理，1：已处理）',
  `batch_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '过程图片批次id',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新人',
  `alert_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '提醒类型  0预警提醒，1警报提醒 2控制',
  `monitor_alert_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '设备报警类型 1.监测点报警 2.塔机报警 3.升降机报警 4.环境报警',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_alert_type_point` (`alert_type`,`monitor_point_id`)
) ENGINE=InnoDB AUTO_INCREMENT=208 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='监测点警报';

CREATE TABLE `monitor_value` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `monitor_point_id` int DEFAULT NULL COMMENT '监测点id',
  `equipment_id` int DEFAULT NULL COMMENT '设备id',
  `monitor_data` varchar(255) DEFAULT NULL COMMENT '监测数据',
  `monitor_time` datetime DEFAULT NULL COMMENT '监测时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2723 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='监测点值表';

CREATE TABLE `spray_system` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `monitor_point_id` int DEFAULT NULL COMMENT '监测点ID',
  `location_id` int DEFAULT NULL COMMENT '位置ID',
  `equipment_id` int DEFAULT NULL COMMENT '设备ID',
  `trigger_type` int DEFAULT NULL COMMENT '触发类型 1：设备监测点越界触发 2：定时任务',
  `operation_type` varchar(2) DEFAULT NULL COMMENT '操作类型 1：启动 0：关闭 2：操作异常',
  `operation_reason` varchar(255) DEFAULT NULL COMMENT '操作原因',
  `operation_time` datetime DEFAULT NULL COMMENT '操作时间',
  PRIMARY KEY (`id`),
  KEY `idx_spray_system_operation_type` (`operation_type`),
  KEY `idx_spray_system_operation_time` (`operation_time`),
  KEY `idx_spray_system_type_time` (`operation_type`,`operation_time`),
  KEY `idx_spray_system_equipment_id` (`equipment_id`),
  KEY `idx_spray_system_location_id` (`location_id`)
) ENGINE=InnoDB AUTO_INCREMENT=242 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='自动喷淋系统表';

CREATE TABLE `spray_task` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_name` varchar(255) DEFAULT NULL COMMENT '任务名称',
  `start_time` datetime DEFAULT NULL COMMENT '启动时间',
  `next_time` datetime DEFAULT NULL COMMENT '下次执行时间',
  `duration` int DEFAULT '1' COMMENT '喷淋时长，单位：分钟',
  `cycle` int DEFAULT '10' COMMENT '执行周期',
  `location_id` int DEFAULT '25' COMMENT '地点id',
  `cycle_unit` varchar(50) DEFAULT NULL COMMENT '执行周期单位（字典项）',
  `is_enable` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '1' COMMENT '启停状态，0：禁用；1：启动（非字典项）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='喷淋定期任务表';

CREATE TABLE `tower_data` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `asset_id` int DEFAULT NULL COMMENT '设备ID',
  `monitor_time` datetime DEFAULT NULL COMMENT '监测时间',
  `weight` decimal(5,2) DEFAULT '0.00' COMMENT '吊重（单位是t）0.00~99.99',
  `amplitude` decimal(5,2) DEFAULT '0.00' COMMENT '幅度（单位是M）0.00~99.99',
  `obliguity` decimal(5,2) DEFAULT '0.00' COMMENT '倾角-9.99~9.99°',
  `wind_speed` decimal(5,2) DEFAULT '0.00' COMMENT '风速（单位是m/s）0.00~36.90',
  `moment` decimal(10,2) DEFAULT '0.00' COMMENT '力矩 M*T',
  `height` decimal(6,2) DEFAULT '0.00' COMMENT '高度（单位是M）-100~655.35',
  `rotation` int DEFAULT '0' COMMENT '转角（单位是度）-540~540',
  PRIMARY KEY (`id`),
  KEY `idx_monitor_time` (`monitor_time`),
  KEY `idx_equipment_id` (`asset_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1445 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='塔机设备实时数据表';

CREATE TABLE `tower_info` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID，自增生成唯一标识',
  `asset_id` int NOT NULL COMMENT '设备ID，关联设备表唯一标识',
  `forward_arm_length` decimal(10,2) DEFAULT NULL COMMENT '前向臂长，记录塔机前向臂的长度数值',
  `backward_arm_length` decimal(10,2) DEFAULT NULL COMMENT '后向臂长，记录塔机后向臂的长度数值',
  `max_height` decimal(10,2) DEFAULT NULL COMMENT '最大吊高',
  `rated_load` decimal(10,2) DEFAULT NULL COMMENT '额定吊重，塔机正常工作状态下的额定起吊重量',
  `max_load` decimal(10,2) DEFAULT NULL COMMENT '最大吊重，塔机可承受的最大起吊重量上限',
  `rated_moment` decimal(12,2) DEFAULT NULL COMMENT '额定力矩，塔机正常工作状态下的额定力矩数值',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间，数据插入时自动记录当前时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间，数据修改时自动更新为当前时间',
  PRIMARY KEY (`id`) COMMENT '主键约束，确保id字段唯一性',
  UNIQUE KEY `uk_asset_id` (`asset_id`) COMMENT '唯一索引，确保asset_id字段无重复值'
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='塔机信息表，存储塔机设备的基础参数信息';

CREATE TABLE `tower_work` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `asset_id` int DEFAULT NULL COMMENT '塔机id',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `weight` double DEFAULT NULL COMMENT '平均吊重 t',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注信息',
  `create_time` datetime DEFAULT NULL COMMENT '记录创建时间',
  `max_radius` double DEFAULT NULL COMMENT '最大幅度 m',
  `start_angle` double DEFAULT NULL COMMENT '起始回转角度 °',
  `max_percent` double DEFAULT NULL COMMENT '最大力矩百分比 %',
  `max_height` double DEFAULT NULL COMMENT '最大高度 m',
  `end_angle` double DEFAULT NULL COMMENT '卸吊点的回转角度 °',
  `min_radius` double DEFAULT NULL COMMENT '本次吊物过程中的最小幅度 m',
  `max_load` double DEFAULT NULL COMMENT '本次吊物过程中的最大起重量 t',
  `max_wind_speed` double DEFAULT NULL COMMENT '本次吊物最大风速 m/s',
  `min_height` double DEFAULT NULL COMMENT '本次吊物过程中的最小高度 m',
  `lifting_point_radius` float DEFAULT NULL COMMENT '起吊点幅度 m',
  `lifting_point_height` float DEFAULT NULL COMMENT '起吊点高度 m',
  `lifting_point_radius_unload` float DEFAULT NULL COMMENT '卸吊点幅度 m',
  `lifting_point_height_unload` float DEFAULT NULL COMMENT '卸吊点高度 m',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=147 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='塔机效果数据实体类';

SET FOREIGN_KEY_CHECKS = 1;
